# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kaytu < Formula
  desc ""
  homepage "https://github.com/adorigi/kaytu"
  version "4.2.15"

  on_macos do
    on_intel do
      url "https://github.com/adorigi/kaytu/releases/download/v4.2.15/kaytu_4.2.15_darwin_amd64.tar.gz"
      sha256 "7bba3fb5237aef798185b8d593b38a60dfcb2b716d2586051075c7168cce4aa8"

      def install
        bin.install "kaytu"
      end
    end
    on_arm do
      url "https://github.com/adorigi/kaytu/releases/download/v4.2.15/kaytu_4.2.15_darwin_arm64.tar.gz"
      sha256 "e9a540718fc5cd399fe614e83d563c3f338cf762dde36c0035ab10d95d13ec8d"

      def install
        bin.install "kaytu"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adorigi/kaytu/releases/download/v4.2.15/kaytu_4.2.15_linux_amd64.tar.gz"
        sha256 "52ed0864ed8535aa9f87034c8591cc85c538943021f716391b2433aba1599e2f"

        def install
          bin.install "kaytu"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adorigi/kaytu/releases/download/v4.2.15/kaytu_4.2.15_linux_arm64.tar.gz"
        sha256 "b1f1f892deb5fee4d8e96cfa4f2dd9bb597d47f652abc004aae3c351119826e4"

        def install
          bin.install "kaytu"
        end
      end
    end
  end
end
