# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KaytuCli < Formula
  desc ""
  homepage "https://github.com/adorigi/kaytu"
  version "0.1.13"

  on_macos do
    on_intel do
      url "https://github.com/adorigi/kaytu/releases/download/v0.1.13/kaytu_0.1.13_darwin_amd64.tar.gz"
      sha256 "28e634a863ad15db05cb6b1ed223efd15c5a16a85c1ed36f766d674b80d26e6c"

      def install
        bin.install "kaytu"
      end
    end
    on_arm do
      url "https://github.com/adorigi/kaytu/releases/download/v0.1.13/kaytu_0.1.13_darwin_arm64.tar.gz"
      sha256 "19285d441c8d813d2603c187effdb4c89f74838becf3661c053050760724b074"

      def install
        bin.install "kaytu"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adorigi/kaytu/releases/download/v0.1.13/kaytu_0.1.13_linux_amd64.tar.gz"
        sha256 "4bbf5ab2f597029f839e103283e309b0fd9a8b5b9f089b04aabce0ea0b199776"

        def install
          bin.install "kaytu"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adorigi/kaytu/releases/download/v0.1.13/kaytu_0.1.13_linux_arm64.tar.gz"
        sha256 "68a1e73e5704dc849bf543b94534542927120dae34b64786501e678f0554dd7a"

        def install
          bin.install "kaytu"
        end
      end
    end
  end
end
