# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KaytuCli < Formula
  desc ""
  homepage "https://github.com/adorigi/kaytu"
  version "0.1.12"

  on_macos do
    on_intel do
      url "https://github.com/adorigi/kaytu/releases/download/v0.1.12/kaytu_0.1.12_darwin_amd64.tar.gz"
      sha256 "63498a3f3cc92a769a67dde5347413dec16e8bf61d3c03b4aceefe10186f1998"

      def install
        bin.install "kaytu"
      end
    end
    on_arm do
      url "https://github.com/adorigi/kaytu/releases/download/v0.1.12/kaytu_0.1.12_darwin_arm64.tar.gz"
      sha256 "919a0289c150c5cd5f059d8b68e3de40d56853c6a962b0f19a75494956e4a87a"

      def install
        bin.install "kaytu"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adorigi/kaytu/releases/download/v0.1.12/kaytu_0.1.12_linux_amd64.tar.gz"
        sha256 "10667e342c647341d67b3f4d124491b53131bc2c33f1d8625f71576111e77ebc"

        def install
          bin.install "kaytu"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adorigi/kaytu/releases/download/v0.1.12/kaytu_0.1.12_linux_arm64.tar.gz"
        sha256 "d18e05f7074c3d2620ef1fc0c6cc2dc22d0b66f47655d65f1c5d0d24d17fcdfd"

        def install
          bin.install "kaytu"
        end
      end
    end
  end
end
