# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kaytu < Formula
  desc ""
  homepage "https://github.com/adorigi/kaytu"
  version "4.3.17"

  on_macos do
    on_intel do
      url "https://github.com/adorigi/kaytu/releases/download/v4.3.17/kaytu_4.3.17_darwin_amd64.tar.gz"
      sha256 "ea9e8a9d8ca944dfea1ce4bd69d455bb80f4a6497b02e6e5147f46ec70c3cd98"

      def install
        bin.install "kaytu"
      end
    end
    on_arm do
      url "https://github.com/adorigi/kaytu/releases/download/v4.3.17/kaytu_4.3.17_darwin_arm64.tar.gz"
      sha256 "d1c002b3d5b6166382c77ee7615226b59dda286ecc964a06b5df6022f81d0f99"

      def install
        bin.install "kaytu"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adorigi/kaytu/releases/download/v4.3.17/kaytu_4.3.17_linux_amd64.tar.gz"
        sha256 "c831bc360ffe3217f12f46ad628b0283ca234a394b4d8f619729d0a44855e862"

        def install
          bin.install "kaytu"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adorigi/kaytu/releases/download/v4.3.17/kaytu_4.3.17_linux_arm64.tar.gz"
        sha256 "eec5c04ee8f9bef44be6210ddedd642becbcd8239acdca09f6b74dff233bc5e8"

        def install
          bin.install "kaytu"
        end
      end
    end
  end
end
