# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KaytuCli < Formula
  desc ""
  homepage "https://github.com/adorigi/kaytu"
  version "0.1.14"

  on_macos do
    on_intel do
      url "https://github.com/adorigi/kaytu/releases/download/v0.1.14/kaytu_0.1.14_darwin_amd64.tar.gz"
      sha256 "1c89965152090e9370b5b3cb0f765261297eb8342ca2cc23be55a58bc06ad406"

      def install
        bin.install "kaytu"
      end
    end
    on_arm do
      url "https://github.com/adorigi/kaytu/releases/download/v0.1.14/kaytu_0.1.14_darwin_arm64.tar.gz"
      sha256 "03eca55a027fea4c58a6c5f50be61746ef39eb55e60bb8c3b6c0abcd9af4126c"

      def install
        bin.install "kaytu"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adorigi/kaytu/releases/download/v0.1.14/kaytu_0.1.14_linux_amd64.tar.gz"
        sha256 "cd31c4051125860c32b5fa821c4fedbc79ee42bd841c19a678b605f73a5c290c"

        def install
          bin.install "kaytu"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adorigi/kaytu/releases/download/v0.1.14/kaytu_0.1.14_linux_arm64.tar.gz"
        sha256 "e81f2e89be9e46071b2e3779fb1898934a9ca7898e6af7ef012eb05c128c216b"

        def install
          bin.install "kaytu"
        end
      end
    end
  end
end
