# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kaytu < Formula
  desc ""
  homepage "https://github.com/adorigi/kaytu"
  version "4.3.25"

  on_macos do
    on_intel do
      url "https://github.com/adorigi/kaytu/releases/download/v4.3.25/kaytu_4.3.25_darwin_amd64.tar.gz"
      sha256 "67a9e57c24ae997b14403349d1572ca1fa46ffe709d2cc0e369b8aba7267db90"

      def install
        bin.install "kaytu"
      end
    end
    on_arm do
      url "https://github.com/adorigi/kaytu/releases/download/v4.3.25/kaytu_4.3.25_darwin_arm64.tar.gz"
      sha256 "040aa2ce0ac3d179f74c799d79a95e116cb24166051aed95f19c269cb5df26f1"

      def install
        bin.install "kaytu"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adorigi/kaytu/releases/download/v4.3.25/kaytu_4.3.25_linux_amd64.tar.gz"
        sha256 "9ab48a310abec915be023daf3f9a4b9c969d99b2f72610ea1a37c724b96e82a6"

        def install
          bin.install "kaytu"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adorigi/kaytu/releases/download/v4.3.25/kaytu_4.3.25_linux_arm64.tar.gz"
        sha256 "4d482841928e91099726129082e150c9d48cabd1b808d3a6eefb5cdddde85535"

        def install
          bin.install "kaytu"
        end
      end
    end
  end
end
