# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SyndicateCli < Formula
  desc ""
  homepage "https://github.com/adorigi/syndicate-cli"
  version "0.1.4-rc"

  on_macos do
    url "https://github.com/ADorigi/syndicate-cli/releases/download/0.1.4-rc/syndicate-cli_0.1.4-rc_darwin_all.tar.gz"
    sha256 "6cfa4da94f96058b2d69d9830f7ab58dc8d7bc233c11bca3a643e68c6ee62d39"

    def install
      bin.install "syndicate-cli"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ADorigi/syndicate-cli/releases/download/0.1.4-rc/syndicate-cli_0.1.4-rc_linux_amd64.tar.gz"
        sha256 "26624b6b5e4ba2b8986f0e859ce3fb42fb2f3d81038c2a4f8c92fae3130d9a3a"

        def install
          bin.install "syndicate-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ADorigi/syndicate-cli/releases/download/0.1.4-rc/syndicate-cli_0.1.4-rc_linux_arm64.tar.gz"
        sha256 "6082a5a1c555ac5ef11be46b53a593d6970c22f9730a2c7ec8fa6725e1ba4663"

        def install
          bin.install "syndicate-cli"
        end
      end
    end
  end
end
