# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SyndicateCli < Formula
  desc ""
  homepage "https://github.com/adorigi/syndicate-cli"
  version "0.1.3"

  on_macos do
    url "https://github.com/ADorigi/syndicate-cli/releases/download/0.1.3/syndicate-cli_0.1.3_darwin_all.tar.gz"
    sha256 "4fb4a131960f86a4131ab138196b91a6f93e2da4aa7cf633f13898cb79ea7c27"

    def install
      bin.install "syndicate-cli"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ADorigi/syndicate-cli/releases/download/0.1.3/syndicate-cli_0.1.3_linux_amd64.tar.gz"
        sha256 "89e8649a14393456d7272f6a7c3c0f7b761c652976c07d2052f7bf158d46e082"

        def install
          bin.install "syndicate-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ADorigi/syndicate-cli/releases/download/0.1.3/syndicate-cli_0.1.3_linux_arm64.tar.gz"
        sha256 "d491d1c1fce48d60a744f6f9d4c5d370332f6e5187ef72c648378234f7acdae6"

        def install
          bin.install "syndicate-cli"
        end
      end
    end
  end
end
